"""Shared 480×800 player layout constants (no Tk dependency)."""

PW = 480
PH = 800

SCENE_TOP = 108
SCENE_W = 340
SCENE_H = 212
SCENE_X = (PW - SCENE_W) // 2

NODE_FRAME_W = int(PW * 0.68)
NODE_FRAME_H = int(NODE_FRAME_W * 666 / 1182)
NODE_FRAME_X = (PW - NODE_FRAME_W) // 2
NODE_FRAME_Y = SCENE_TOP + SCENE_H + 18
NODE_FRAME_BORDER = 0.05

TEXT_WRAP_W = int(NODE_FRAME_W * (1 - 2 * NODE_FRAME_BORDER))
TEXT_CY = NODE_FRAME_H // 2 + 2
TEXT_BODY_SIZE = 8
NODE_ID_TEXT_SIZE = 6

BTN_SIZE = 88
BTN_Y = PH - 112
CHOICE_GAP = 62
CHOICE_LX = PW // 2 - CHOICE_GAP
CHOICE_RX = PW // 2 + CHOICE_GAP
CHOICE_TEXT_Y = BTN_Y - BTN_SIZE // 2 - 14
CHOICE_W = 168

TRACE_H = 22
TRACE_Y = PH - TRACE_H - 6
